using System.Text.Json.Serialization;

namespace SpaceTraders.Core;

public class SpaceTradersErrorResponse
{
    [JsonPropertyName("error")]
    public SpaceTradersError Error { get; set; } = default!;
}

public class SpaceTradersErrorResponse<TData> where TData: class
{
    [JsonPropertyName("error")]
    public SpaceTradersError<TData> Error { get; set; } = default!;
}

/// <summary>
/// `2xx` indicate success
/// `4xx` indicate error in information provided
/// `5xx` indicate error in api
/// </summary>
public class SpaceTradersError
{
    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

    [JsonPropertyName("code")]
    public ErrorCodes ErrorCode { get; set; } = ErrorCodes.UNKNOWN_ERROR; 
}

/// <summary>
/// `2xx` indicate success
/// `4xx` indicate error in information provided
/// `5xx` indicate error in api
/// </summary>
public class SpaceTradersError<TError> : SpaceTradersError where TError : class
{
    [JsonPropertyName("data")]
    public TError? Data { get; set; } = null;
}

public enum ErrorCodes
{
    UNKNOWN_ERROR = 0,
    
    // GENERAL ERROR CODES
    COOLDOWN_CONFLICT_ERROR = 4000,
    WAYPOINT_NO_ACCESS_ERROR = 4001,
    
    // ACCOUNT ERROR CODES
    TOKEN_EMPTY_ERROR = 4100,
    TOKEN_MISSING_SUBJECT_ERROR = 4101,
    TOKEN_INVALID_SUBJECT_ERROR = 4102,
    MISSING_TOKEN_REQUEST_ERROR = 4103,
    INVALID_TOKEN_REQUEST_ERROR = 4104,
    INVALID_TOKEN_SUBJECT_ERROR = 4105,
    ACCOUNT_NOT_EXISTS_ERROR = 4106,
    AGENT_NOT_EXISTS_ERROR = 4107,
    ACCOUNT_HAS_NO_AGENT_ERROR = 4108,
    REGISTER_AGENT_EXISTS_ERROR = 4109,
    
    // SHIP ERROR CODES
    NAVIGATE_IN_TRANSIT_ERROR = 4200,
    NAVIGATE_INVALID_DESTINATION_ERROR = 4201,
    NAVIGATE_OUTSIDE_SYSTEM_ERROR = 4202,
    NAVIGATE_INSUFFICIENT_FUEL_ERROR = 4203,
    NAVIGATE_SAME_DESTINATION_ERROR = 4204,
    SHIP_EXTRACT_INVALID_WAYPOINT_ERROR = 4205,
    SHIP_EXTRACT_PERMISSION_ERROR = 4206,
    SHIP_JUMP_NO_SYSTEM_ERROR = 4207,
    SHIP_JUMP_SAME_SYSTEM_ERROR = 4208,
    SHIP_JUMP_MISSING_MODULE_ERROR = 4210,
    SHIP_JUMP_NO_VALID_WAYPOINT_ERROR = 4211,
    SHIP_JUMP_MISSING_ANTIMATTER_ERROR = 4212,
    SHIP_IN_TRANSIT_ERROR = 4214,
    SHIP_MISSING_SENSOR_ARRAYS_ERROR = 4215,
    PURCHASE_SHIP_CREDITS_ERROR = 4216,
    SHIP_CARGO_EXCEEDS_LIMIT_ERROR = 4217,
    SHIP_CARGO_MISSING_ERROR = 4218,
    SHIP_CARGO_UNIT_COUNT_ERROR = 4219,
    SHIP_SURVEY_VERIFICATION_ERROR = 4220,
    SHIP_SURVEY_EXPIRATION_ERROR = 4221,
    SHIP_SURVEY_WAYPOINT_TYPE_ERROR = 4222,
    SHIP_SURVEY_ORBIT_ERROR = 4223,
    SHIP_SURVEY_EXHAUSTED_ERROR = 4224,
    SHIP_REFUEL_DOCKED_ERROR = 4225,
    SHIP_REFUEL_INVALID_WAYPOINT_ERROR = 4226,
    SHIP_MISSING_MOUNTS_ERROR = 4227,
    SHIP_CARGO_FULL_ERROR = 4228,
    SHIP_JUMP_FROM_GATE_TO_GATE_ERROR = 4229,
    WAYPOINT_CHARTED_ERROR = 4230,
    SHIP_TRANSFER_SHIP_NOT_FOUND = 4231,
    SHIP_TRANSFER_AGENT_CONFLICT = 4232,
    SHIP_TRANSFER_SAME_SHIP_CONFLICT = 4233,
    SHIP_TRANSFER_LOCATION_CONFLICT = 4234,
    WARP_INSIDE_SYSTEM_ERROR = 4235,
    SHIP_NOT_IN_ORBIT_ERROR = 4236,
    SHIP_INVALID_REFINERY_GOOD_ERROR = 4237,
    SHIP_INVALID_REFINERY_TYPE_ERROR = 4238,
    SHIP_MISSING_REFINERY_ERROR = 4239,
    SHIP_MISSING_SURVEYOR_ERROR = 4240,
    
    // CONTRACT ERROR CODES
    ACCEPT_CONTRACT_NOT_AUTHORIZED_ERROR = 4500,
    ACCEPT_CONTRACT_CONFLICT_ERROR = 4501,
    FULFILL_CONTRACT_DELIVERY_ERROR = 4502,
    CONTRACT_DEADLINE_ERROR = 4503,
    CONTRACT_FULFILLED_ERROR = 4504,
    CONTRACT_NOT_ACCEPTED_ERROR = 4505,
    CONTRACT_NOT_AUTHORIZED_ERROR = 4506,
    SHIP_DELIVER_TERMS_ERROR = 4508,
    SHIP_DELIVER_FULFILLED_ERROR = 4509,
    SHIP_DELIVER_INVALID_LOCATION_ERROR = 4510,
    
    // MARKET ERROR CODES
    MARKET_TRADE_INSUFFICIENT_CREDITS_ERROR = 4600,
    MARKET_TRADE_NO_PURCHASE_ERROR = 4601,
    MARKET_TRADE_NOT_SOLD_ERROR = 4602,
    MARKET_NOT_FOUND_ERROR = 4603,
    MARKET_TRADE_UNIT_LIMIT_ERROR = 4604,
}